# Generated by Django 5.1.7 on 2025-06-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='valor_proposta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor principal da proposta', max_digits=12, verbose_name='Valor da Proposta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposta',
            name='numero',
            field=models.CharField(max_length=8, unique=True, verbose_name='Número da Proposta'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=20),
        ),
        migrations.AddIndex(
            model_name='proposta',
            index=models.Index(fields=['valor_proposta'], name='core_propos_valor_p_239ef6_idx'),
        ),
    ]
