# Generated by Django 5.1.7 on 2025-05-23 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fornecedor', models.CharField(blank=True, help_text='Código que o fornecedor usa para este produto', max_length=50, verbose_name='Código do Fornecedor')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço Unitário')),
                ('prioridade', models.IntegerField(choices=[(1, 'Principal'), (2, 'Secundário'), (3, 'Terceiro'), (4, 'Backup')], default=2, verbose_name='Prioridade')),
                ('prazo_entrega', models.IntegerField(blank=True, null=True, verbose_name='Prazo Entrega (dias)')),
                ('quantidade_minima', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade Mínima')),
                ('observacoes', models.TextField(blank=True, help_text='Condições especiais, descontos, etc.', verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultima_cotacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Cotação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor_produto_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_fornecedor', to='core.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_produto', to='core.produto')),
            ],
            options={
                'verbose_name': 'Fornecedor do Produto',
                'verbose_name_plural': 'Fornecedores dos Produtos',
                'ordering': ['prioridade', '-ativo', 'fornecedor__razao_social'],
                'unique_together': {('produto', 'fornecedor')},
            },
        ),
    ]
