# Generated by Django 5.1.7 on 2025-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proposta_valor_proposta_alter_proposta_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='altura_cabine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura da Cabine (m)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='altura_porta_cabine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura Porta Cabine (m)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='altura_porta_pavimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura Porta Pavimento (m)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='espessura_cabine',
            field=models.CharField(blank=True, choices=[('1,2', '1,2 mm'), ('1,5', '1,5 mm'), ('2,0', '2,0 mm')], max_length=10, null=True, verbose_name='Espessura'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='largura_porta_cabine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largura Porta Cabine (m)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='largura_porta_pavimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largura Porta Pavimento (m)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_cabine',
            field=models.CharField(blank=True, choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Material da Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_cabine',
            field=models.CharField(blank=True, choices=[('Inox', 'Inox'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Material Porta Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Inox', 'Inox'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Material Porta Pavimento'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='modelo_porta_cabine',
            field=models.CharField(blank=True, choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina'), ('Camarão', 'Camarão'), ('Cancela', 'Cancela'), ('Rampa', 'Rampa')], max_length=20, null=True, verbose_name='Modelo Porta Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='modelo_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina'), ('Camarão', 'Camarão'), ('Cancela', 'Cancela'), ('Rampa', 'Rampa')], max_length=20, null=True, verbose_name='Modelo Porta Pavimento'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='piso_cabine',
            field=models.CharField(blank=True, choices=[('Por conta do cliente', 'Por conta do cliente'), ('Por conta da empresa', 'Por conta da empresa')], max_length=50, null=True, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='saida_cabine',
            field=models.CharField(blank=True, choices=[('Padrão', 'Padrão'), ('Oposta', 'Oposta')], max_length=20, null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_proposta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor principal da proposta', max_digits=12, null=True, verbose_name='Valor da Proposta'),
        ),
    ]
