# Generated by Django 5.1.7 on 2025-05-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Digite apenas números ou use a formatação padrão', max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_cnpj__isnull', False), models.Q(('cpf_cnpj', ''), _negated=True)), fields=('cpf_cnpj',), name='unique_cpf_cnpj_not_empty'),
        ),
    ]
