# Generated by Django 5.1.7 on 2025-06-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proposta_altura_cabine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='preco_sem_impostos',
        ),
        migrations.AlterField(
            model_name='proposta',
            name='preco_venda_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço de venda sugerido pelo sistema, antes da negociação', max_digits=12, null=True, verbose_name='Preço de Venda Calculado'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_proposta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor principal da proposta (pode ser negociado)', max_digits=12, null=True, verbose_name='Valor da Proposta'),
        ),
    ]
