# Generated by Django 5.1.7 on 2025-06-19 21:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_proposta_preco_sem_impostos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaMateriais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('calculando', 'Calculando'), ('pronta', 'Pronta'), ('editada', 'Editada'), ('aprovada', 'Aprovada')], default='calculando', max_length=20, verbose_name='Status')),
                ('dados_calculo_original', models.JSONField(blank=True, default=dict, verbose_name='Dados Cálculo Original')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listas_materiais_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_materiais_criadas', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_materiais', to='core.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Lista de Materiais',
                'verbose_name_plural': 'Listas de Materiais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Orçamento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Orçamento')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('cotando', 'Em Cotação'), ('cotado', 'Cotado'), ('analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('data_orcamento', models.DateField(default=datetime.date.today, verbose_name='Data do Orçamento')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('data_necessidade', models.DateField(blank=True, null=True, verbose_name='Data de Necessidade')),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Estimado')),
                ('valor_total_cotado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Cotado')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('comprador_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_comprador', to=settings.AUTH_USER_MODEL, verbose_name='Comprador Responsável')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_solicitante', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Orçamento de Compra',
                'verbose_name_plural': 'Orçamentos de Compra',
                'ordering': ['-data_orcamento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOrcamentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.orcamentocompra')),
            ],
            options={
                'verbose_name': 'Histórico do Orçamento',
                'verbose_name_plural': 'Histórico dos Orçamentos',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da Requisição')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('cotando', 'Em Cotação'), ('orcada', 'Orçada'), ('aprovada', 'Aprovada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('data_requisicao', models.DateField(default=datetime.date.today, verbose_name='Data da Requisição')),
                ('data_necessidade', models.DateField(blank=True, null=True, verbose_name='Data de Necessidade')),
                ('departamento', models.CharField(default='Produção', max_length=50, verbose_name='Departamento')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_compras', models.TextField(blank=True, verbose_name='Observações do Setor de Compras')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('lista_materiais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='core.listamateriais', verbose_name='Lista de Materiais')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Requisição de Compra',
                'verbose_name_plural': 'Requisições de Compra',
                'ordering': ['-data_requisicao', '-numero'],
            },
        ),
        migrations.AddField(
            model_name='orcamentocompra',
            name='requisicoes',
            field=models.ManyToManyField(related_name='orcamentos', to='core.requisicaocompra', verbose_name='Requisições'),
        ),
        migrations.CreateModel(
            name='ItemRequisicaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('valor_unitario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário Estimado')),
                ('valor_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Estimado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='core.produto')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.requisicaocompra')),
            ],
            options={
                'verbose_name': 'Item da Requisição',
                'verbose_name_plural': 'Itens das Requisições',
                'ordering': ['produto__codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemListaMateriais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('valor_unitario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário Estimado')),
                ('valor_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Estimado')),
                ('item_calculado', models.BooleanField(default=True, help_text='Se foi calculado automaticamente ou adicionado manualmente', verbose_name='Item Calculado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_lista_materiais', to='core.produto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.listamateriais')),
            ],
            options={
                'verbose_name': 'Item da Lista de Materiais',
                'verbose_name_plural': 'Itens das Listas de Materiais',
                'ordering': ['produto__codigo'],
                'unique_together': {('lista', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('valor_unitario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário Estimado')),
                ('valor_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Estimado')),
                ('valor_unitario_cotado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário Cotado')),
                ('valor_total_cotado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Cotado')),
                ('prazo_entrega', models.IntegerField(blank=True, null=True, verbose_name='Prazo Entrega (dias)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_cotacao', models.TextField(blank=True, verbose_name='Observações da Cotação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='core.fornecedor', verbose_name='Fornecedor Selecionado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='core.produto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.orcamentocompra')),
            ],
            options={
                'verbose_name': 'Item do Orçamento',
                'verbose_name_plural': 'Itens dos Orçamentos',
                'ordering': ['produto__codigo'],
                'unique_together': {('orcamento', 'produto')},
            },
        ),
        migrations.AddIndex(
            model_name='requisicaocompra',
            index=models.Index(fields=['numero'], name='core_requis_numero_9c0bad_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaocompra',
            index=models.Index(fields=['status'], name='core_requis_status_41a78b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaocompra',
            index=models.Index(fields=['data_requisicao'], name='core_requis_data_re_ad6f61_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentocompra',
            index=models.Index(fields=['numero'], name='core_orcame_numero_9b486a_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentocompra',
            index=models.Index(fields=['status'], name='core_orcame_status_16e1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamentocompra',
            index=models.Index(fields=['data_orcamento'], name='core_orcame_data_or_0a0be4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemrequisicaocompra',
            unique_together={('requisicao', 'produto')},
        ),
    ]
