# Generated by Django 5.1.7 on 2025-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
    ]
