# Generated by Django 5.1.7 on 2025-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_listamateriais_orcamentocompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='preco_negociado',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='preco_venda_final',
        ),
        migrations.AddField(
            model_name='proposta',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='3% sobre preço com margem', max_digits=12, null=True, verbose_name='Comissão'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='custo_indiretos_fabricacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='5% dos materiais - energia, depreciação, etc.', max_digits=12, null=True, verbose_name='Custos Indiretos de Fabricação'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='custo_total_projeto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo de Produção + Custo de Instalação', max_digits=12, null=True, verbose_name='Custo Total do Projeto'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='impostos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='10% sobre preço com comissão', max_digits=12, null=True, verbose_name='Impostos'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='margem_lucro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='30% sobre custo total do projeto', max_digits=12, null=True, verbose_name='Margem de Lucro'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='preco_com_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço com Margem + Comissão', max_digits=12, null=True, verbose_name='Preço com Comissão'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='preco_com_margem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo Total + Margem de Lucro', max_digits=12, null=True, verbose_name='Preço com Margem'),
        ),
        migrations.AlterField(
            model_name='listamateriais',
            name='status',
            field=models.CharField(choices=[('calculando', 'Calculando'), ('em_edicao', 'Em Edição'), ('aprovada', 'Aprovada')], default='calculando', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='custo_instalacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='5% dos materiais - serviços no cliente', max_digits=12, null=True, verbose_name='Custo de Instalação'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='custo_mao_obra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='15% dos materiais - MOD para fabricação', max_digits=12, null=True, verbose_name='Custo de Mão de Obra Produção'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='custo_materiais',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Materiais diretos (cabine + carrinho + tração + sistemas)', max_digits=12, null=True, verbose_name='Custo de Materiais'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='custo_producao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Materiais + MOD + Custos Indiretos (SEM instalação)', max_digits=12, null=True, verbose_name='Custo de Produção'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de desconto sobre o preço calculado', max_digits=5, verbose_name='Desconto Aplicado (%)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='preco_venda_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço sugerido pelo sistema (com todos os componentes)', max_digits=12, null=True, verbose_name='Preço de Venda Calculado'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('simulado', 'Simulado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_proposta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor final negociado com o cliente', max_digits=12, null=True, verbose_name='Valor da Proposta'),
        ),
    ]
