# Generated by Django 5.1.7 on 2025-05-24 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fornecedor_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MP', 'Matéria Prima'), ('PI', 'Produto Intermediário'), ('PA', 'Produto Acabado')], max_length=2, unique=True, verbose_name='Tipo de Produto')),
                ('prefixo', models.CharField(help_text='Prefixo usado nos códigos (ex: MP, PI, PA)', max_length=5, verbose_name='Prefixo')),
                ('proximo_numero', models.PositiveIntegerField(default=1, verbose_name='Próximo Número')),
                ('numero_digitos', models.PositiveIntegerField(default=4, help_text='Quantidade de dígitos para o número sequencial', verbose_name='Número de Dígitos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequência de Produto',
                'verbose_name_plural': 'Sequências de Produtos',
                'db_table': 'sequencia_produto',
            },
        ),
        migrations.CreateModel(
            name='ParametrosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(help_text='Razão social da empresa', max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ da empresa (apenas números)', max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('margem_padrao', models.DecimalField(decimal_places=2, default=30.0, help_text='Margem de lucro padrão aplicada nas simulações', max_digits=5, verbose_name='Margem Padrão (%)')),
                ('faturamento_elevadores', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentual de faturamento sobre vendas de elevadores', max_digits=5, verbose_name='Faturamento Elevadores (%)')),
                ('faturamento_fuza', models.DecimalField(decimal_places=2, default=3.0, help_text='Percentual de faturamento FUZA sobre o valor', max_digits=5, verbose_name='Faturamento FUZA (%)')),
                ('faturamento_manutencao', models.DecimalField(decimal_places=2, default=2.0, help_text='Percentual de faturamento para serviços de manutenção', max_digits=5, verbose_name='Faturamento Manutenção (%)')),
                ('comissao_padrao', models.DecimalField(decimal_places=2, default=5.0, help_text='Comissão padrão para vendedores', max_digits=5, verbose_name='Comissão Padrão (%)')),
                ('desconto_alcada_1', models.DecimalField(decimal_places=2, default=10.0, help_text='Limite máximo de desconto para vendedores', max_digits=5, verbose_name='Desconto Alçada 1 (%)')),
                ('desconto_alcada_2', models.DecimalField(decimal_places=2, default=20.0, help_text='Limite máximo de desconto para gestores', max_digits=5, verbose_name='Desconto Alçada 2 (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametros_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametros_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parâmetros Gerais',
                'verbose_name_plural': 'Parâmetros Gerais',
                'db_table': 'parametros_gerais',
            },
        ),
    ]
