# Generated by Django 5.1.7 on 2025-05-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sequenciaproduto_parametrosgerais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosgerais',
            name='comissao_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='desconto_alcada_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='desconto_alcada_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='faturamento_elevadores',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='faturamento_fuza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='faturamento_manutencao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='margem_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
