# Generated by Django 5.1.7 on 2025-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_proposta_preco_negociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='utilizado',
            field=models.BooleanField(default=False, help_text='Indica se este material já foi utilizado em algum projeto', verbose_name='Material Utilizado'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('simulado', 'Simulado'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=20),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['utilizado'], name='core_produt_utiliza_1a1d63_idx'),
        ),
    ]
