# Generated by Django 5.1.7 on 2025-05-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_parametrosgerais_comissao_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosgerais',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
