# Generated by Django 5.1.7 on 2025-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_utilizado_alter_proposta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='contrapeso',
            field=models.CharField(blank=True, choices=[('Traseiro', 'Traseiro'), ('Lateral', 'Lateral')], max_length=20, null=True, verbose_name='Contrapeso'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='tracao',
            field=models.CharField(blank=True, choices=[('1x1', '1x1'), ('2x1', '2x1')], max_length=10, null=True, verbose_name='Tração'),
        ),
    ]
