# Generated by Django 5.1.7 on 2025-06-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_proposta_contrapeso_alter_proposta_tracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'nivel': 'vendedor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
