# Generated by Django 5.1.7 on 2025-05-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_parametrosgerais_bairro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SequenciaProduto',
        ),
    ]
