# Generated by Django 5.1.7 on 2025-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_sequenciaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoproduto',
            name='tipo_produto',
            field=models.CharField(choices=[('MP', 'Matéria Prima'), ('PI', 'Produto Intermediário'), ('PA', 'Produto Acabado')], default='MP', help_text='Define se este grupo é para Matéria Prima, Produto Intermediário ou Produto Acabado', max_length=2, verbose_name='Tipo de Produto'),
        ),
        migrations.AddField(
            model_name='subgrupoproduto',
            name='ultimo_numero',
            field=models.IntegerField(default=0, help_text='Último número sequencial usado para produtos deste subgrupo', verbose_name='Último Número'),
        ),
    ]
