# Generated by Django 5.1.7 on 2025-07-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_proposta_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='contrapeso',
            field=models.CharField(blank=True, choices=[('Traseiro', 'Traseiro'), ('Lateral', 'Lateral')], default='Traseiro', max_length=20, verbose_name='Contrapeso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposta',
            name='folhas_porta_pavimento',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('Central', 'Central')], max_length=10, verbose_name='Folhas Porta Pavimento (Único)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Inox', 'Inox'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Material Porta Pavimento (Único)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='modelo_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina'), ('Camarão', 'Camarão'), ('Cancela', 'Cancela'), ('Rampa', 'Rampa')], help_text='Usado quando todas as portas são iguais', max_length=20, null=True, verbose_name='Modelo Porta Pavimento (Único)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='tracao',
            field=models.CharField(blank=True, choices=[('1x1', '1x1'), ('2x1', '2x1')], default='1x1', max_length=10, verbose_name='Tração'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposta',
            name='vendedor',
            field=models.ForeignKey(default=1, limit_choices_to={'nivel': 'vendedor'}, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PortaPavimentoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Ex: 'Porta Padrão Residencial', 'Porta Garagem', etc.", max_length=100, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, help_text='Descrição de onde usar este template', verbose_name='Descrição')),
                ('modelo_padrao', models.CharField(choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina'), ('Camarão', 'Camarão'), ('Cancela', 'Cancela'), ('Rampa', 'Rampa')], max_length=20, verbose_name='Modelo Padrão')),
                ('material_padrao', models.CharField(choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, verbose_name='Material Padrão')),
                ('folhas_padrao', models.CharField(blank=True, choices=[('2', '2 Folhas'), ('3', '3 Folhas'), ('Central', 'Central')], max_length=10, verbose_name='Folhas Padrão')),
                ('largura_padrao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Largura Padrão (m)')),
                ('altura_padrao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Altura Padrão (m)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Porta',
                'verbose_name_plural': 'Templates de Portas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PortaPavimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andar', models.IntegerField(help_text='Número do andar (0=Térreo, 1=1º andar, etc.)', verbose_name='Andar')),
                ('nome_andar', models.CharField(help_text='Ex: Térreo, 1º Andar, Subsolo, etc.', max_length=50, verbose_name='Nome do Andar')),
                ('modelo', models.CharField(choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina'), ('Camarão', 'Camarão'), ('Cancela', 'Cancela'), ('Rampa', 'Rampa')], max_length=20, verbose_name='Modelo da Porta')),
                ('material', models.CharField(choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, verbose_name='Material')),
                ('material_outro', models.CharField(blank=True, help_text="Especifique quando Material = 'Outro'", max_length=100, verbose_name='Material Personalizado')),
                ('valor_material_outro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Material Personalizado')),
                ('folhas', models.CharField(blank=True, choices=[('2', '2 Folhas'), ('3', '3 Folhas'), ('Central', 'Central')], help_text='Aplicável apenas para portas automáticas', max_length=10, verbose_name='Número de Folhas')),
                ('largura', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Largura (m)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Altura (m)')),
                ('observacoes', models.TextField(blank=True, help_text='Características especiais deste pavimento', verbose_name='Observações')),
                ('custo_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Custo específico desta porta (calculado automaticamente)', max_digits=12, null=True, verbose_name='Custo Calculado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem para exibição na interface', verbose_name='Ordem de Exibição')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas_pavimento', to='core.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Porta do Pavimento',
                'verbose_name_plural': 'Portas dos Pavimentos',
                'ordering': ['proposta', 'ordem', 'andar'],
                'indexes': [models.Index(fields=['proposta', 'andar'], name='core_portap_propost_8fa1e3_idx'), models.Index(fields=['proposta', 'ordem'], name='core_portap_propost_eb2573_idx')],
                'unique_together': {('proposta', 'andar')},
            },
        ),
    ]
