# Generated by Django 5.1.7 on 2025-06-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_grupoproduto_tipo_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupoproduto',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_produtos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_principal', to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.grupoproduto', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.subgrupoproduto'),
        ),
        migrations.AlterField(
            model_name='subgrupoproduto',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos_produtos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
