# Generated by Django 5.1.7 on 2025-06-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fornecedor_criado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoproduto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='subgrupoproduto',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='grupoproduto',
            name='tipo_produto',
            field=models.CharField(choices=[('MP', 'Matéria Prima'), ('PI', 'Produto Intermediário'), ('PA', 'Produto Acabado')], default='MP', max_length=2, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='subgrupoproduto',
            name='ultimo_numero',
            field=models.IntegerField(default=0, verbose_name='Último Número'),
        ),
    ]
