# Generated by Django 5.1.7 on 2025-07-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_proposta_contrapeso_alter_proposta_tracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portapavimentotemplate',
            name='criado_por',
        ),
        migrations.AlterModelOptions(
            name='portapavimento',
            options={'ordering': ['proposta', 'andar'], 'verbose_name': 'Porta do Pavimento', 'verbose_name_plural': 'Portas dos Pavimentos'},
        ),
        migrations.RemoveIndex(
            model_name='portapavimento',
            name='core_portap_propost_8fa1e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='portapavimento',
            name='core_portap_propost_eb2573_idx',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='custo_calculado',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='folhas',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='material_outro',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='valor_material_outro',
        ),
        migrations.AlterField(
            model_name='portapavimento',
            name='andar',
            field=models.IntegerField(verbose_name='Andar'),
        ),
        migrations.AlterField(
            model_name='portapavimento',
            name='material',
            field=models.CharField(choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='portapavimento',
            name='modelo',
            field=models.CharField(choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portapavimento',
            name='nome_andar',
            field=models.CharField(max_length=50, verbose_name='Nome do Andar'),
        ),
        migrations.AlterField(
            model_name='portapavimento',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas_pavimento', to='core.proposta'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='folhas_porta_pavimento',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('Central', 'Central')], max_length=10, null=True, verbose_name='Folhas Porta Pavimento'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Inox', 'Inox'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Material Porta Pavimento'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='modelo_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina'), ('Camarão', 'Camarão'), ('Cancela', 'Cancela'), ('Rampa', 'Rampa')], max_length=20, null=True, verbose_name='Modelo Porta Pavimento'),
        ),
        migrations.DeleteModel(
            name='PortaPavimentoTemplate',
        ),
    ]
