# Generated by Django 5.1.7 on 2025-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_portapavimentotemplate_criado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portapavimento',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='portapavimento',
            name='largura',
        ),
        migrations.AlterField(
            model_name='proposta',
            name='folhas_porta_pavimento',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('Central', 'Central')], default=2, max_length=10, verbose_name='Folhas Porta Pavimento'),
            preserve_default=False,
        ),
    ]
