# Generated by Django 5.1.7 on 2025-06-09 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_grupoproduto_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pedido')),
                ('data_entrega_prevista', models.DateField(blank=True, null=True, verbose_name='Data Entrega Prevista')),
                ('data_entrega_real', models.DateField(blank=True, null=True, verbose_name='Data Entrega Real')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('CONFIRMADO', 'Confirmado'), ('PARCIAL', 'Parcialmente Recebido'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=15)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto %')),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto R$')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Frete')),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Final')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Condição de Pagamento')),
                ('prazo_entrega', models.IntegerField(blank=True, null=True, verbose_name='Prazo Entrega (dias)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-data_pedido', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Recebida')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data Recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='core.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedidocompra')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens dos Pedidos de Compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.pedidocompra')),
            ],
            options={
                'verbose_name': 'Histórico do Pedido',
                'verbose_name_plural': 'Histórico dos Pedidos',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['numero'], name='core_pedido_numero_4be619_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['fornecedor', 'status'], name='core_pedido_fornece_edda83_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['data_pedido'], name='core_pedido_data_pe_02bfc5_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['status'], name='core_pedido_status_8b2c03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedidocompra',
            unique_together={('pedido', 'produto')},
        ),
    ]
