# Generated by Django 5.1.7 on 2025-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_portapavimento_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_cabine',
            field=models.CharField(blank=True, choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Material Porta Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Material Porta Pavimento'),
        ),
    ]
