# Generated by Django 5.1.7 on 2025-06-10 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pedidocompra_itempedidocompra_historicopedidocompra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'ordering': ['-data_emissao', '-numero'], 'verbose_name': 'Pedido de Compra', 'verbose_name_plural': 'Pedidos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.RemoveIndex(
            model_name='pedidocompra',
            name='core_pedido_data_pe_02bfc5_idx',
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='data_pedido',
        ),
        migrations.AddField(
            model_name='parametrosgerais',
            name='comprador_responsavel',
            field=models.CharField(blank=True, help_text='Nome do responsável pelas compras', max_length=100, verbose_name='Comprador Responsável'),
        ),
        migrations.AddField(
            model_name='parametrosgerais',
            name='contato_compras',
            field=models.CharField(blank=True, help_text='Email ou telefone do setor de compras', max_length=100, verbose_name='Contato de Compras'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='comprador_responsavel',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente dos parâmetros', max_length=100, verbose_name='Comprador Responsável'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='contato_compras',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente dos parâmetros', max_length=100, verbose_name='Contato de Compras'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='data_emissao',
            field=models.DateField(default=datetime.date.today, help_text='Data de emissão do pedido', verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='data_entrega_prevista',
            field=models.DateField(blank=True, help_text='Calculada automaticamente com base na data de emissão + prazo', null=True, verbose_name='Data Entrega Prevista'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='prazo_entrega',
            field=models.IntegerField(default=7, help_text='Prazo de entrega em dias úteis', verbose_name='Prazo de Entrega (dias)'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['data_emissao'], name='core_pedido_data_em_de9a62_idx'),
        ),
    ]
