# Generated by Django 5.1.7 on 2025-07-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_proposta_material_porta_cabine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='normas_abnt',
            field=models.CharField(choices=[('NBR 16858', 'NBR 16858 - 2024'), ('NBR 16042', 'NBR 16042 - 2020')], default='NBR 16858', help_text='Norma técnica aplicável ao elevador', max_length=20, verbose_name='Normas ABNT'),
        ),
    ]
