# Generated by Django 5.1.7 on 2025-07-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_proposta_normas_abnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_ncm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código NCM'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_produto_fornecedor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código no Fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_industrializacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Industrialização'),
        ),
    ]
