# Generated by Django 5.1.7 on 2025-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_produto_codigo_ncm_produto_codigo_produto_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_pi',
            field=models.CharField(blank=True, choices=[('COMPRADO', 'Comprado Pronto'), ('MONTADO_INTERNO', 'Montado Internamente'), ('MONTADO_EXTERNO', 'Montado Externamente'), ('SERVICO', 'Serviço')], help_text='Apenas para Produtos Intermediários (PI)', max_length=20, null=True, verbose_name='Tipo do Produto Intermediário'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tipo_pi'], name='core_produt_tipo_pi_be4458_idx'),
        ),
    ]
