# Generated by Django 5.1.7 on 2025-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_produto_tipo_pi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_pi',
            field=models.CharField(blank=True, choices=[('COMPRADO', 'Comprado Pronto'), ('MONTADO_INTERNO', 'Montado Internamente'), ('MONTADO_EXTERNO', 'Montado Externamente'), ('SERVICO_INTERNO', 'Serviço Interno'), ('SERVICO_EXTERNO', 'Serviço Externo')], help_text='Apenas para Produtos Intermediários (PI)', max_length=20, null=True, verbose_name='Tipo do Produto Intermediário'),
        ),
    ]
