# Generated by Django 5.1.7 on 2025-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_produto_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo_material',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo de materiais/componentes do produto', max_digits=10, null=True, verbose_name='Custo Material'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_servico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo de mão de obra/serviços do produto', max_digits=10, null=True, verbose_name='Custo Serviço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_industrializacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo mantido para compatibilidade. Use custo_servico', max_digits=10, null=True, verbose_name='Custo Industrialização (Legacy)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_medio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo mantido para compatibilidade. Use custo_material + custo_servico', max_digits=10, null=True, verbose_name='Custo Médio (Legacy)'),
        ),
    ]
