# Generated by Django 5.1.7 on 2025-08-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_restaurar_produtos_excel'),
    ]

    operations = [
        # Pode manter essa remoção (não participa de unique_together)
        migrations.RemoveField(
            model_name='especificacaoelevador',
            name='criado_por',
        ),

        # 1) ZERAR unique_together ANTES de remover campos que participam do índice
        migrations.AlterUniqueTogether(
            name='opcaoespecificacao',
            unique_together=set(),
        ),

        # 2) Agora remover os campos com segurança
        migrations.RemoveField(
            model_name='opcaoespecificacao',
            name='especificacao',
        ),
        migrations.RemoveField(
            model_name='opcaoespecificacao',
            name='criado_por',
        ),

        migrations.RemoveField(
            model_name='regracomponente',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='regracomponente',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='simulacaoelevador',
            name='criado_por',
        ),

        # 3) Por fim, deletar os modelos
        migrations.DeleteModel(
            name='ComponenteDerivado',
        ),
        migrations.DeleteModel(
            name='EspecificacaoElevador',
        ),
        migrations.DeleteModel(
            name='OpcaoEspecificacao',
        ),
        migrations.DeleteModel(
            name='RegraComponente',
        ),
        migrations.DeleteModel(
            name='SimulacaoElevador',
        ),
    ]