# Generated by Django 5.1.7 on 2025-08-10 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_especificacaoelevador_criado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraYAML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cabine', 'Cabine'), ('carrinho', 'Carrinho'), ('tracao', 'Tração'), ('sistemas', 'Sistemas')], help_text='Tipo da regra (cabine, carrinho, tração, sistemas)', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome descritivo da regra', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do que a regra faz')),
                ('conteudo_yaml', models.TextField(help_text='Conteúdo da regra em formato YAML')),
                ('versao', models.PositiveIntegerField(default=1, help_text='Versão da regra para controle de mudanças')),
                ('ativa', models.BooleanField(default=True, help_text='Se a regra está ativa e deve ser utilizada')),
                ('validado', models.BooleanField(default=False, help_text='Se a regra foi validada e todos os códigos existem')),
                ('ultimo_erro', models.TextField(blank=True, help_text='Último erro encontrado na validação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_yaml_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_yaml_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra YAML',
                'verbose_name_plural': 'Regras YAML',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
