# Generated by Django 5.1.7 on 2025-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_regrayaml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regrayaml',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='regrayaml',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='regrayaml',
            name='conteudo_yaml',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='regrayaml',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='regrayaml',
            name='tipo',
            field=models.CharField(choices=[('cabine', 'Cabine'), ('carrinho', 'Carrinho'), ('tracao', 'Tração'), ('sistemas', 'Sistemas')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='regrayaml',
            name='ultimo_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='regrayaml',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regrayaml',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
