# Generated by Django 5.1.7 on 2025-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_regrayaml_descricao_alter_regrayaml_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='previsao_conclusao_obra',
            field=models.DateField(blank=True, help_text='Data prevista para conclusão da obra civil', null=True, verbose_name='Previsão Conclusão da Obra'),
        ),
    ]
