# Generated by Django 5.1.7 on 2025-08-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_proposta_previsao_conclusao_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='altura_poco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura do Poço (m)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='comprimento_poco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Comprimento do Poço (m)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='largura_poco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largura do Poço (m)'),
        ),
    ]
