# Generated by Django 5.1.7 on 2025-09-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_proposta_altura_poco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='data_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='documentacao_prefeitura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposta',
            name='local_instalacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
