# Generated by Django 5.1.7 on 2025-09-06 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_proposta_data_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='material_cabine_outro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='material_piso_cabine_outro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='material_porta_cabine_outro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='material_porta_pavimento_outro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_cabine_outro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_piso_cabine_outro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_porta_cabine_outro',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_porta_pavimento_outro',
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_proxima_vistoria',
            field=models.DateField(blank=True, help_text='Data agendada para próxima vistoria', null=True, verbose_name='Data da Próxima Vistoria'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_vistoria_medicao',
            field=models.DateField(blank=True, help_text='Data da primeira vistoria para medição', null=True, verbose_name='Data da Vistoria/Medição'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='status_obra',
            field=models.CharField(blank=True, choices=[('', 'Aguardando Medição'), ('medicao_ok', 'Medição OK'), ('em_vistoria', 'Em Vistoria'), ('obra_ok', 'Obra OK')], help_text='Status do acompanhamento da obra civil', max_length=20, verbose_name='Status da Obra'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='folhas_porta_cabine',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('Central', 'Central')], max_length=10, verbose_name='Folhas Porta Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='folhas_porta_pavimento',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('Central', 'Central')], max_length=10, verbose_name='Folhas Porta Pavimento'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_cabine',
            field=models.CharField(blank=True, choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio')], max_length=50, null=True, verbose_name='Material da Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_piso_cabine',
            field=models.CharField(blank=True, choices=[('Antiderrapante', 'Antiderrapante')], max_length=50, verbose_name='Material do Piso'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_cabine',
            field=models.CharField(blank=True, choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio')], max_length=50, null=True, verbose_name='Material Porta Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='material_porta_pavimento',
            field=models.CharField(blank=True, choices=[('Inox 430', 'Inox 430'), ('Inox 304', 'Inox 304'), ('Chapa Pintada', 'Chapa Pintada'), ('Alumínio', 'Alumínio')], max_length=50, null=True, verbose_name='Material Porta Pavimento'),
        ),
        migrations.CreateModel(
            name='VistoriaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField(verbose_name='Data Agendada')),
                ('data_realizada', models.DateField(blank=True, null=True, verbose_name='Data Realizada')),
                ('tipo_vistoria', models.CharField(choices=[('medicao', 'Medição Inicial'), ('acompanhamento', 'Acompanhamento'), ('obra_pronta', 'Obra Pronta'), ('entrega', 'Entrega')], default='acompanhamento', max_length=20, verbose_name='Tipo de Vistoria')),
                ('status_vistoria', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('reagendada', 'Reagendada')], default='agendada', max_length=20, verbose_name='Status da Vistoria')),
                ('status_obra_anterior', models.CharField(blank=True, max_length=20, verbose_name='Status Anterior da Obra')),
                ('status_obra_novo', models.CharField(blank=True, max_length=20, verbose_name='Novo Status da Obra')),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais da vistoria', verbose_name='Observações')),
                ('recomendacoes', models.TextField(blank=True, help_text='Recomendações técnicas e pendências', verbose_name='Recomendações')),
                ('proxima_vistoria_sugerida', models.DateField(blank=True, null=True, verbose_name='Próxima Vistoria Sugerida')),
                ('fotos_anexos', models.JSONField(blank=True, default=list, help_text='Lista de URLs/caminhos para fotos e anexos', verbose_name='Fotos e Anexos')),
                ('dados_tecnicos', models.JSONField(blank=True, default=dict, help_text='Medições, condições da obra, etc.', verbose_name='Dados Técnicos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vistorias_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='core.proposta')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Vistoria')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-data_agendada', '-criado_em'],
                'indexes': [models.Index(fields=['proposta', '-data_agendada'], name='core_vistor_propost_4b7324_idx'), models.Index(fields=['responsavel', 'data_agendada'], name='core_vistor_respons_79c8a9_idx'), models.Index(fields=['status_vistoria'], name='core_vistor_status__2aa31f_idx'), models.Index(fields=['tipo_vistoria'], name='core_vistor_tipo_vi_3ae1df_idx')],
            },
        ),
    ]
