# Generated by Django 5.1.7 on 2025-09-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_proposta_material_cabine_outro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='documentacao_prefeitura',
            field=models.CharField(choices=[('cliente', 'Por conta do cliente'), ('empresa', 'Por conta da empresa')], default='cliente', max_length=20, verbose_name='Documentação Prefeitura'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=20),
        ),
    ]
