# Generated by Django 5.1.7 on 2025-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_proposta_documentacao_prefeitura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, help_text='Data em que a proposta foi aprovada', null=True, verbose_name='Data de Aprovação'),
        ),
    ]
