# Generated by Django 5.1.7 on 2025-09-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_proposta_data_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora quando a proposta foi aprovada', null=True, verbose_name='Data de Aprovação'),
        ),
    ]
