# Generated by Django 5.1.7 on 2025-09-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_proposta_data_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriahistorico',
            name='alteracoes_realizadas',
            field=models.TextField(blank=True, help_text='Resumo das alterações feitas durante esta vistoria', verbose_name='Alterações Realizadas'),
        ),
    ]
