# Generated by Django 5.1.7 on 2025-09-15 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_vistoriahistorico_alteracoes_realizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='portapavimento',
            name='abertura_porta',
            field=models.CharField(choices=[('direita', 'Direita'), ('esquerda', 'Esquerda')], default='direita', max_length=10, verbose_name='Abertura da Porta'),
        ),
        migrations.AddField(
            model_name='portapavimento',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.10'), help_text='Altura específica da porta deste pavimento', max_digits=5, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='portapavimento',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque se este pavimento não terá porta', verbose_name='Pavimento Ativo'),
        ),
        migrations.AddField(
            model_name='portapavimento',
            name='folhas',
            field=models.CharField(blank=True, choices=[('2', '2 Folhas'), ('3', '3 Folhas'), ('4', '4 Folhas'), ('Central', 'Central')], help_text='Aplicável apenas para portas automáticas', max_length=10, verbose_name='Número de Folhas'),
        ),
        migrations.AddField(
            model_name='portapavimento',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='Largura específica da porta deste pavimento', max_digits=5, verbose_name='Largura (m)'),
        ),
        migrations.AddField(
            model_name='portapavimento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Características especiais deste pavimento', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='portapavimento',
            name='saida',
            field=models.CharField(choices=[('normal', 'Normal'), ('oposta', 'Oposta')], default='normal', max_length=10, verbose_name='Saída do Elevador'),
        ),
        migrations.AlterField(
            model_name='portapavimento',
            name='modelo',
            field=models.CharField(choices=[('Automática', 'Automática'), ('Pantográfica', 'Pantográfica'), ('Pivotante', 'Pivotante'), ('Guilhotina', 'Guilhotina'), ('Camarão', 'Camarão'), ('Cancela', 'Cancela'), ('Rampa', 'Rampa')], max_length=20),
        ),
    ]
