# Generated by Django 5.1.7 on 2025-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_portapavimento_abertura_porta_portapavimento_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='abertura_cabine',
            field=models.CharField(choices=[('direita', 'Direita'), ('esquerda', 'Esquerda')], default='direita', max_length=10, verbose_name='Abertura da Cabine'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='tipo_motor',
            field=models.CharField(blank=True, choices=[('com_engrenagem', 'Com Engrenagem'), ('sem_engrenagem', 'Sem Engrenagem')], help_text='Aplicável apenas para acionamento tipo Motor', max_length=20, null=True, verbose_name='Tipo Motor'),
        ),
    ]
