# Generated by Django 5.1.7 on 2025-09-16 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_proposta_abertura_cabine_proposta_tipo_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriahistorico',
            name='casa_maquina_altura',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Altura Casa de Máquina (m)'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='casa_maquina_energia',
            field=models.BooleanField(default=False, verbose_name='Ponto de Energia'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='casa_maquina_gancho',
            field=models.BooleanField(default=False, verbose_name='Gancho Instalado'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='casa_maquina_obs',
            field=models.TextField(blank=True, verbose_name='Observações Casa de Máquina'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='cintas_distancia',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Distância entre Cintas (m)'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='cintas_largura',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Largura das Cintas (m)'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='cintas_obs',
            field=models.TextField(blank=True, verbose_name='Observações das Cintas'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='fosso_altura',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Altura medida do fosso', max_digits=8, null=True, verbose_name='Altura do Fosso (m)'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='fosso_largura',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Largura do Fosso (m)'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='fosso_obs',
            field=models.TextField(blank=True, help_text='Condições, problemas ou observações específicas', verbose_name='Observações do Fosso'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='fosso_profundidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Profundidade do Fosso (m)'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='poco_largura',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Largura do Poço (m)'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='poco_obs',
            field=models.TextField(blank=True, verbose_name='Observações do Poço'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='poco_profundidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Profundidade do Poço (m)'),
        ),
        migrations.CreateModel(
            name='VaoPortaVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavimento', models.CharField(help_text='Ex: Térreo, 1º Andar, 2º Andar, etc.', max_length=20, verbose_name='Pavimento')),
                ('largura', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Largura do Vão (m)')),
                ('altura', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Altura do Vão (m)')),
                ('observacoes', models.TextField(blank=True, help_text='Condições específicas deste pavimento', verbose_name='Observações')),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaos_porta', to='core.vistoriahistorico')),
            ],
            options={
                'verbose_name': 'Vão de Porta',
                'verbose_name_plural': 'Vãos de Porta',
                'ordering': ['pavimento'],
                'unique_together': {('vistoria', 'pavimento')},
            },
        ),
    ]
