# Generated by Django 5.1.7 on 2025-10-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_vistoriahistorico_casa_maquina_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaocompra',
            name='lista_materiais',
            field=models.ForeignKey(blank=True, help_text='Opcional - Se não informada, adicione itens manualmente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='core.listamateriais', verbose_name='Lista de Materiais'),
        ),
    ]
