# Generated by Django 5.1.7 on 2025-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_requisicaocompra_lista_materiais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listamateriais',
            options={'ordering': ['-criado_em'], 'permissions': [('aprovar_lista_materiais', 'Pode aprovar lista de materiais'), ('editar_lista_materiais_aprovada', 'Pode editar lista de materiais já aprovada'), ('visualizar_custos_lista', 'Pode visualizar custos da lista de materiais')], 'verbose_name': 'Lista de Materiais', 'verbose_name_plural': 'Listas de Materiais'},
        ),
        migrations.AlterModelOptions(
            name='orcamentocompra',
            options={'ordering': ['-data_orcamento', '-numero'], 'permissions': [('aprovar_orcamento_ate_5000', 'Pode aprovar orçamentos até R$ 5.000'), ('aprovar_orcamento_ate_10000', 'Pode aprovar orçamentos até R$ 10.000'), ('aprovar_orcamento_ate_50000', 'Pode aprovar orçamentos até R$ 50.000'), ('aprovar_orcamento_ilimitado', 'Pode aprovar orçamentos sem limite de valor'), ('cancelar_orcamento', 'Pode cancelar orçamentos'), ('editar_orcamento_aprovado', 'Pode editar orçamentos já aprovados')], 'verbose_name': 'Orçamento de Compra', 'verbose_name_plural': 'Orçamentos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-criado_em'], 'permissions': [('aprovar_desconto_5', 'Pode aprovar desconto até 5%'), ('aprovar_desconto_10', 'Pode aprovar desconto até 10%'), ('aprovar_desconto_15', 'Pode aprovar desconto até 15%'), ('aprovar_desconto_20', 'Pode aprovar desconto até 20%'), ('aprovar_desconto_ilimitado', 'Pode aprovar desconto ilimitado'), ('visualizar_custos', 'Pode visualizar custos e margens'), ('visualizar_todas_propostas', 'Pode visualizar propostas de outros vendedores'), ('exportar_relatorios', 'Pode exportar relatórios'), ('editar_proposta_alheia', 'Pode editar propostas de outros vendedores'), ('aprovar_proposta', 'Pode aprovar propostas'), ('rejeitar_proposta', 'Pode rejeitar propostas'), ('realizar_vistoria', 'Pode realizar vistorias'), ('agendar_vistoria', 'Pode agendar vistorias'), ('aprovar_medicao', 'Pode aprovar medições de obra')], 'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
        migrations.AlterModelOptions(
            name='requisicaocompra',
            options={'ordering': ['-data_requisicao', '-numero'], 'permissions': [('aprovar_requisicao', 'Pode aprovar requisições de compra'), ('cancelar_requisicao', 'Pode cancelar requisições de compra'), ('editar_requisicao_aprovada', 'Pode editar requisições já aprovadas')], 'verbose_name': 'Requisição de Compra', 'verbose_name_plural': 'Requisições de Compra'},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('vendedor', 'Vendedor'), ('compras', 'Compras'), ('engenharia', 'Engenharia'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria'), ('producao', 'Produção')], default='vendedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('vendedor', 'Vendedor'), ('compras', 'Compras'), ('engenharia', 'Engenharia'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria'), ('producao', 'Produção')], max_length=20),
        ),
    ]
