# Generated by Django 5.1.7 on 2025-10-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_usuario_groups_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('vendedor', 'Vendedor'), ('compras', 'Compras'), ('engenharia', 'Engenharia'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria'), ('producao', 'Produção'), ('almoxarifado', 'Almoxarifado')], default='vendedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('vendedor', 'Vendedor'), ('compras', 'Compras'), ('engenharia', 'Engenharia'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria'), ('producao', 'Produção'), ('almoxarifado', 'Almoxarifado')], max_length=20),
        ),
    ]
