# Generated by Django 5.1.7 on 2025-10-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_perfilusuario_nivel_alter_usuario_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequisicaocompra',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='item_requisicao',
            field=models.ForeignKey(blank=True, help_text='Item da requisição que este pedido atende', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='core.itemrequisicaocompra', verbose_name='Item da Requisição'),
        ),
        migrations.AddField(
            model_name='itemrequisicaocompra',
            name='quantidade_em_pedido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade já incluída em pedidos de compra', max_digits=10, verbose_name='Quantidade em Pedido'),
        ),
        migrations.AddField(
            model_name='itemrequisicaocompra',
            name='quantidade_recebida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade já recebida no estoque', max_digits=10, verbose_name='Quantidade Recebida'),
        ),
        migrations.AddField(
            model_name='itemrequisicaocompra',
            name='quantidade_solicitada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Solicitada'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='orcamento',
            field=models.ForeignKey(blank=True, help_text='Opcional - Orçamento que gerou este pedido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.orcamentocompra', verbose_name='Orçamento de Origem'),
        ),
    ]
