# Generated by Django 5.1.7 on 2025-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_itemrequisicaocompra_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequisicaocompra',
            name='quantidade_cancelada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de saldo cancelada/não mais necessária (reversível)', max_digits=10, verbose_name='Quantidade Cancelada'),
        ),
    ]
