# Generated by Django 5.1.7 on 2025-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_itemrequisicaocompra_quantidade_cancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequisicaocompra',
            name='quantidade_cancelada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Quantidade de saldo cancelada/não mais necessária (reversível)', max_digits=10, verbose_name='Quantidade Cancelada'),
        ),
    ]
