# Generated by Django 5.1.7 on 2025-11-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_itemrequisicaocompra_quantidade_cancelada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedidocompra',
            unique_together=set(),
        ),
    ]
