# Generated by Django 5.1.7 on 2025-11-02 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0045_remove_unique_produto_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário (DEPRECADO)', 'verbose_name_plural': 'Perfis de Usuários (DEPRECADO)'},
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('projeto_executivo', 'Enviar Projeto Executivo'), ('criar_lista_materiais', 'Criar Lista de Materiais'), ('criar_orcamentos', 'Criar Orçamentos de Compra'), ('aprovar_orcamentos', 'Aprovar Orçamentos'), ('iniciar_producao', 'Iniciar Produção'), ('agendar_instalacao', 'Agendar Instalação'), ('outro', 'Outra Tarefa')], max_length=50, verbose_name='Tipo da Tarefa')),
                ('titulo', models.CharField(help_text='Descrição curta da tarefa', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes adicionais sobre a tarefa', null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Quando a tarefa foi iniciada', null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('prazo', models.DateField(blank=True, help_text='Data limite para conclusão', null=True, verbose_name='Prazo')),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre a conclusão da tarefa', null=True, verbose_name='Observações')),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Concluída Por')),
                ('criada_por', models.ForeignKey(blank=True, help_text='Usuário que criou a tarefa (ou sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada Por')),
                ('grupo_destino', models.ForeignKey(blank=True, help_text='Grupo que deve executar a tarefa (ex: Engenharia, Compras)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='auth.group', verbose_name='Grupo Responsável')),
                ('lista_materiais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.listamateriais', verbose_name='Lista de Materiais Relacionada')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.proposta', verbose_name='Proposta Relacionada')),
                ('requisicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.requisicaocompra', verbose_name='Requisição Relacionada')),
                ('usuario_destino', models.ForeignKey(blank=True, help_text='Usuário específico responsável (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'workflow_tarefas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(help_text='criada, iniciada, concluida, cancelada, atribuida', max_length=50, verbose_name='Ação')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes da ação realizada', verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Histórico de Tarefa',
                'verbose_name_plural': 'Histórico de Tarefas',
                'db_table': 'workflow_historico_tarefas',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['status', 'grupo_destino'], name='workflow_ta_status_569351_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['status', 'usuario_destino'], name='workflow_ta_status_80283a_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['proposta', 'status'], name='workflow_ta_propost_e734e4_idx'),
        ),
    ]
