# Generated by Django 5.1.7 on 2025-11-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0046_alter_perfilusuario_options_tarefa_historicotarefa_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tarefa',
            name='workflow_ta_status_569351_idx',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='nivel_destino',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('vendedor', 'Vendedor'), ('compras', 'Compras'), ('engenharia', 'Engenharia'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria'), ('producao', 'Produção'), ('almoxarifado', 'Almoxarifado')], help_text='Nível que deve executar a tarefa (ex: engenharia, compras)', max_length=50, null=True, verbose_name='Nível Responsável'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='grupo_destino',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED - Use nivel_destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='auth.group', verbose_name='Grupo Responsável (DEPRECATED)'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['status', 'nivel_destino'], name='workflow_ta_status_a807f0_idx'),
        ),
    ]
