# Generated by Django 5.1.7 on 2025-11-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_nivel_destino_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='arquivo_projeto_elevador',
            field=models.FileField(blank=True, help_text='PDF do projeto do elevador', null=True, upload_to='projetos/elevadores/%Y/%m/', verbose_name='Arquivo Projeto Elevador'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='arquivo_projeto_executivo',
            field=models.FileField(blank=True, help_text='PDF do projeto executivo', null=True, upload_to='projetos/executivos/%Y/%m/', verbose_name='Arquivo Projeto Executivo'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_upload_projeto_elevador',
            field=models.DateTimeField(blank=True, help_text='Data e hora do upload do projeto do elevador', null=True, verbose_name='Data Upload Projeto Elevador'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_upload_projeto_executivo',
            field=models.DateTimeField(blank=True, help_text='Data e hora do upload do projeto executivo', null=True, verbose_name='Data Upload Projeto Executivo'),
        ),
    ]
