# Generated by Django 5.1.7 on 2025-11-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_projeto_upload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='data_autorizacao_producao',
            field=models.DateField(blank=True, help_text='Data de autorização para iniciar produção', null=True, verbose_name='Data Autorização Produção'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_compra',
            field=models.DateField(blank=True, help_text='Data de realização das compras de materiais', null=True, verbose_name='Data Compra'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_conclusao',
            field=models.DateField(blank=True, help_text='Data efetiva de conclusão da produção', null=True, verbose_name='Data Conclusão'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_entrega',
            field=models.DateField(blank=True, help_text='Data efetiva de entrega ao cliente', null=True, verbose_name='Data Entrega'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_entrega_obra',
            field=models.DateField(blank=True, help_text='Data efetiva da entrega da obra civil', null=True, verbose_name='Data Entrega Obra'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_inicio_producao',
            field=models.DateField(blank=True, help_text='Data efetiva de início da produção', null=True, verbose_name='Data Início Produção'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_previsao_conclusao',
            field=models.DateField(blank=True, help_text='Data prevista para conclusão da produção', null=True, verbose_name='Data Previsão Conclusão'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_previsao_entrega',
            field=models.DateField(blank=True, help_text='Data prevista para entrega ao cliente', null=True, verbose_name='Data Previsão Entrega'),
        ),
    ]
