# Generated by Django 5.1.7 on 2025-11-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_ciclo_vida_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriahistorico',
            name='assinatura_nome',
            field=models.CharField(blank=True, help_text='Nome de quem assinou a vistoria', max_length=200, verbose_name='Nome do Assinante'),
        ),
        migrations.AddField(
            model_name='vistoriahistorico',
            name='assinatura_url',
            field=models.CharField(blank=True, help_text='URL da assinatura digital no MinIO', max_length=500, verbose_name='URL da Assinatura'),
        ),
    ]
