# Generated by Django 5.1.7 on 2025-12-07 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_adicionar_assinatura_vistoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Local')),
                ('tipo', models.CharField(choices=[('proprio', 'Estoque Próprio'), ('terceiros', 'Em Poder de Terceiros')], default='proprio', max_length=15, verbose_name='Tipo')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_estoque_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Obrigatório se tipo = Em Poder de Terceiros', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locais_estoque', to='core.fornecedor', verbose_name='Fornecedor Responsável')),
            ],
            options={
                'verbose_name': 'Local de Estoque',
                'verbose_name_plural': 'Locais de Estoque',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 1101, 1202, 1902', max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo_parceiro', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('cliente', 'Cliente'), ('interno', 'Interno/Nenhum')], default='fornecedor', help_text='Define se a entrada é de fornecedor, cliente ou interno', max_length=15, verbose_name='Tipo de Parceiro')),
                ('movimenta_terceiros', models.BooleanField(default=False, help_text='Ex: Retorno de beneficiamento baixa estoque de terceiros', verbose_name='Movimenta Estoque em Terceiros')),
                ('exige_nota_fiscal', models.BooleanField(default=False, help_text='Se marcado, NF será obrigatória para este tipo', verbose_name='Exige Nota Fiscal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_movimento_entrada_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Movimento de Entrada',
                'verbose_name_plural': 'Tipos de Movimento de Entrada',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 5101, 5901, 5949', max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo_parceiro', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('cliente', 'Cliente'), ('interno', 'Interno/Nenhum')], default='cliente', help_text='Define se a saída é para cliente, fornecedor ou interno', max_length=15, verbose_name='Tipo de Parceiro')),
                ('movimenta_terceiros', models.BooleanField(default=False, help_text='Ex: Remessa p/ beneficiamento entra no estoque de terceiros', verbose_name='Movimenta Estoque em Terceiros')),
                ('exige_nota_fiscal', models.BooleanField(default=False, help_text='Se marcado, NF será obrigatória para este tipo', verbose_name='Exige Nota Fiscal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_movimento_saida_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Movimento de Saída',
                'verbose_name_plural': 'Tipos de Movimento de Saída',
                'ordering': ['codigo'],
            },
        ),
    ]
