# Generated by Django 5.1.7 on 2025-12-07 14:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_estoque_fase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número Interno')),
                ('numero_nf', models.CharField(blank=True, max_length=20, verbose_name='Número NF')),
                ('serie_nf', models.CharField(blank=True, max_length=5, verbose_name='Série NF')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, verbose_name='Chave de Acesso NFe')),
                ('data_emissao_nf', models.DateField(blank=True, null=True, verbose_name='Data Emissão NF')),
                ('data_movimento', models.DateField(default=datetime.date.today, verbose_name='Data do Movimento')),
                ('data_entrada', models.DateField(default=datetime.date.today, verbose_name='Data da Entrada')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Frete')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Desconto')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='core.cliente', verbose_name='Cliente')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque_criadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='core.fornecedor', verbose_name='Fornecedor')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='core.localestoque', verbose_name='Local de Estoque Destino')),
                ('local_estoque_origem', models.ForeignKey(blank=True, help_text='Para retorno de beneficiamento - de onde está vindo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_origem', to='core.localestoque', verbose_name='Local de Origem (Terceiros)')),
                ('pedido_compra', models.ForeignKey(blank=True, help_text='Opcional - Vincular a um pedido de compra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='core.pedidocompra', verbose_name='Pedido de Compra')),
                ('tipo_movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.tipomovimentoentrada', verbose_name='Tipo de Movimento')),
            ],
            options={
                'verbose_name': 'Movimento de Entrada',
                'verbose_name_plural': 'Movimentos de Entrada',
                'ordering': ['-data_movimento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemMovimentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_entrada', to='core.produto', verbose_name='Produto')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.movimentoentrada', verbose_name='Movimento')),
            ],
            options={
                'verbose_name': 'Item de Entrada',
                'verbose_name_plural': 'Itens de Entrada',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('transferencia_entrada', 'Transferência (Entrada)'), ('transferencia_saida', 'Transferência (Saída)')], max_length=25, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('saldo_anterior', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Saldo Anterior')),
                ('saldo_posterior', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Saldo Posterior')),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Custo Unitário')),
                ('custo_medio_anterior', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Custo Médio Anterior')),
                ('custo_medio_posterior', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Custo Médio Posterior')),
                ('documento_tipo', models.CharField(help_text='entrada, saida, ajuste, op', max_length=30, verbose_name='Tipo de Documento')),
                ('documento_numero', models.CharField(max_length=30, verbose_name='Número do Documento')),
                ('documento_id', models.IntegerField(verbose_name='ID do Documento')),
                ('data_movimento', models.DateField(verbose_name='Data do Movimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque_criados', to=settings.AUTH_USER_MODEL)),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.localestoque', verbose_name='Local de Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número Interno')),
                ('numero_nf', models.CharField(blank=True, max_length=20, verbose_name='Número NF')),
                ('serie_nf', models.CharField(blank=True, max_length=5, verbose_name='Série NF')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, verbose_name='Chave de Acesso NFe')),
                ('data_emissao_nf', models.DateField(blank=True, null=True, verbose_name='Data Emissão NF')),
                ('data_movimento', models.DateField(default=datetime.date.today, verbose_name='Data do Movimento')),
                ('data_saida', models.DateField(default=datetime.date.today, verbose_name='Data da Saída')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Frete')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Desconto')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque', to='core.cliente', verbose_name='Cliente')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque_criadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque', to='core.fornecedor', verbose_name='Fornecedor')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='core.localestoque', verbose_name='Local de Estoque Origem')),
                ('local_estoque_destino', models.ForeignKey(blank=True, help_text='Para remessa p/ beneficiamento - para onde está indo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_destino', to='core.localestoque', verbose_name='Local de Destino (Terceiros)')),
                ('tipo_movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.tipomovimentosaida', verbose_name='Tipo de Movimento')),
            ],
            options={
                'verbose_name': 'Movimento de Saída',
                'verbose_name_plural': 'Movimentos de Saída',
                'ordering': ['-data_movimento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemMovimentoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_saida', to='core.produto', verbose_name='Produto')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.movimentosaida', verbose_name='Movimento')),
            ],
            options={
                'verbose_name': 'Item de Saída',
                'verbose_name_plural': 'Itens de Saída',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Quantidade')),
                ('quantidade_reservada', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Quantidade Reservada')),
                ('custo_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Custo Médio')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Total em Estoque')),
                ('ultima_entrada', models.DateField(blank=True, null=True, verbose_name='Última Entrada')),
                ('ultima_saida', models.DateField(blank=True, null=True, verbose_name='Última Saída')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posicoes', to='core.localestoque', verbose_name='Local de Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posicoes_estoque', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Posição de Estoque',
                'verbose_name_plural': 'Posições de Estoque',
                'ordering': ['produto__codigo', 'local_estoque__nome'],
                'indexes': [models.Index(fields=['produto', 'local_estoque'], name='core_estoqu_produto_a354cc_idx'), models.Index(fields=['quantidade'], name='core_estoqu_quantid_5e2eaa_idx')],
                'unique_together': {('produto', 'local_estoque')},
            },
        ),
        migrations.AddIndex(
            model_name='movimentoentrada',
            index=models.Index(fields=['numero'], name='core_movime_numero_a2d822_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoentrada',
            index=models.Index(fields=['status'], name='core_movime_status_8d05eb_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoentrada',
            index=models.Index(fields=['data_movimento'], name='core_movime_data_mo_52ad26_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoentrada',
            index=models.Index(fields=['fornecedor'], name='core_movime_fornece_fbb2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['produto', 'local_estoque'], name='core_movime_produto_a1a60e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['data_movimento'], name='core_movime_data_mo_41932b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['documento_tipo', 'documento_id'], name='core_movime_documen_708d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentosaida',
            index=models.Index(fields=['numero'], name='core_movime_numero_35f3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentosaida',
            index=models.Index(fields=['status'], name='core_movime_status_8bfbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentosaida',
            index=models.Index(fields=['data_movimento'], name='core_movime_data_mo_b63312_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentosaida',
            index=models.Index(fields=['cliente'], name='core_movime_cliente_135a50_idx'),
        ),
    ]
