# Generated by Django 5.1.7 on 2025-12-07 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_estoque_fase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numero da OP')),
                ('quantidade_planejada', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade Planejada')),
                ('quantidade_produzida', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Quantidade Produzida')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('liberada', 'Liberada'), ('em_producao', 'Em Producao'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=15, verbose_name='Status')),
                ('prioridade', models.PositiveSmallIntegerField(default=5, help_text='1 = Urgente, 5 = Normal, 10 = Baixa', verbose_name='Prioridade')),
                ('data_inicio_planejada', models.DateField(blank=True, null=True, verbose_name='Inicio Planejado')),
                ('data_fim_planejada', models.DateField(blank=True, null=True, verbose_name='Fim Planejado')),
                ('data_inicio_real', models.DateField(blank=True, null=True, verbose_name='Inicio Real')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='Fim Real')),
                ('custo_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Previsto')),
                ('custo_real', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Real')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('liberado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_concluidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_criadas', to=settings.AUTH_USER_MODEL)),
                ('liberado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_liberadas', to=settings.AUTH_USER_MODEL)),
                ('local_destino', models.ForeignKey(help_text='Onde o produto acabado sera armazenado', on_delete=django.db.models.deletion.PROTECT, related_name='ops_destino', to='core.localestoque', verbose_name='Local de Destino')),
                ('local_producao', models.ForeignKey(help_text='Onde a producao acontece', on_delete=django.db.models.deletion.PROTECT, related_name='ops_producao', to='core.localestoque', verbose_name='Local de Producao')),
                ('produto', models.ForeignKey(help_text='Produto a ser fabricado (PA ou PI)', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='core.produto', verbose_name='Produto')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao', to='core.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Ordem de Producao',
                'verbose_name_plural': 'Ordens de Producao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemConsumoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_prevista', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade Prevista')),
                ('quantidade_reservada', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Quantidade Reservada')),
                ('quantidade_consumida', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Quantidade Consumida')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('custo_unitario_previsto', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Custo Unitario Previsto')),
                ('custo_unitario_real', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Custo Unitario Real')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('consumido', 'Consumido'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_consumo_op', to='core.localestoque', verbose_name='Local de Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_op', to='core.produto', verbose_name='Produto')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_consumo', to='core.ordemproducao', verbose_name='Ordem de Producao')),
            ],
            options={
                'verbose_name': 'Item de Consumo OP',
                'verbose_name_plural': 'Itens de Consumo OP',
                'ordering': ['produto__codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['numero'], name='core_ordemp_numero_ce6dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['status'], name='core_ordemp_status_934efb_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['produto'], name='core_ordemp_produto_9bb336_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['data_inicio_planejada'], name='core_ordemp_data_in_68e743_idx'),
        ),
    ]
