# Generated by Django 5.1.7 on 2025-12-07 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_estoque_fase4_ordens_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovimentoentrada',
            name='local_estoque',
            field=models.ForeignKey(blank=True, help_text='Local de destino para este tipo de entrada', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localestoque', verbose_name='Local de Estoque'),
        ),
        migrations.AddField(
            model_name='tipomovimentoentrada',
            name='tipos_produto_permitidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tipos permitidos: MP, PI, PA. Vazio = todos', verbose_name='Tipos de Produto Permitidos'),
        ),
        migrations.AddField(
            model_name='tipomovimentosaida',
            name='local_estoque',
            field=models.ForeignKey(blank=True, help_text='Local de origem para este tipo de saída', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localestoque', verbose_name='Local de Estoque'),
        ),
        migrations.AddField(
            model_name='tipomovimentosaida',
            name='local_estoque_destino',
            field=models.ForeignKey(blank=True, help_text='Local de destino quando movimenta terceiros', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_saida_destino', to='core.localestoque', verbose_name='Local de Destino (Terceiros)'),
        ),
        migrations.AddField(
            model_name='tipomovimentosaida',
            name='tipos_produto_permitidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tipos permitidos: MP, PI, PA. Vazio = todos', verbose_name='Tipos de Produto Permitidos'),
        ),
    ]
