# Generated by Django 5.1.7 on 2025-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_tipos_produto_local_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='data_liberacao_producao',
            field=models.DateField(blank=True, help_text='Data de liberação para produção pelo financeiro', null=True, verbose_name='Data Liberação Produção'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='numero_op',
            field=models.CharField(blank=True, help_text='Número da Ordem de Produção', max_length=20, null=True, verbose_name='Número OP'),
        ),
    ]
