# Generated by Django 5.1.7 on 2025-12-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_numero_op_liberacao_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='status_producao',
            field=models.CharField(blank=True, choices=[('', 'Pendente'), ('liberado', 'Liberado'), ('cancelado', 'Cancelado'), ('em_producao', 'Em Produção'), ('concluido', 'Concluído')], default='', help_text='Status do projeto na produção', max_length=20, verbose_name='Status Produção'),
        ),
    ]
