# Generated by Django 5.1.7 on 2025-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_status_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='status_financeiro',
            field=models.CharField(blank=True, choices=[('', 'Pendente'), ('liberado', 'Liberado')], default='', help_text='Status de liberação financeira para produção', max_length=20, verbose_name='Status Financeiro'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status_producao',
            field=models.CharField(blank=True, choices=[('', 'Aguardando'), ('em_producao', 'Em Produção'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='', help_text='Status do projeto na produção', max_length=20, verbose_name='Status Produção'),
        ),
    ]
