# Generated by Django 5.1.7 on 2025-12-07 20:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_migrate_status_financeiro_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoentrada',
            name='local_estoque',
        ),
        migrations.RemoveField(
            model_name='movimentoentrada',
            name='local_estoque_origem',
        ),
        migrations.RemoveField(
            model_name='movimentosaida',
            name='local_estoque',
        ),
        migrations.RemoveField(
            model_name='movimentosaida',
            name='local_estoque_destino',
        ),
        migrations.RemoveField(
            model_name='tipomovimentoentrada',
            name='local_estoque',
        ),
        migrations.RemoveField(
            model_name='tipomovimentoentrada',
            name='movimenta_terceiros',
        ),
        migrations.RemoveField(
            model_name='tipomovimentoentrada',
            name='tipos_produto_permitidos',
        ),
        migrations.RemoveField(
            model_name='tipomovimentosaida',
            name='local_estoque',
        ),
        migrations.RemoveField(
            model_name='tipomovimentosaida',
            name='local_estoque_destino',
        ),
        migrations.RemoveField(
            model_name='tipomovimentosaida',
            name='movimenta_terceiros',
        ),
        migrations.RemoveField(
            model_name='tipomovimentosaida',
            name='tipos_produto_permitidos',
        ),
        migrations.AddField(
            model_name='tipomovimentoentrada',
            name='tipo_produto',
            field=models.CharField(choices=[('MP', 'Matéria-Prima'), ('PI', 'Produto Intermediário'), ('PA', 'Produto Acabado')], default='MP', help_text='Tipo de produto permitido: MP, PI ou PA', max_length=2, verbose_name='Tipo de Produto'),
        ),
        migrations.AddField(
            model_name='tipomovimentosaida',
            name='tipo_produto',
            field=models.CharField(choices=[('MP', 'Matéria-Prima'), ('PI', 'Produto Intermediário'), ('PA', 'Produto Acabado')], default='MP', help_text='Tipo de produto permitido: MP, PI ou PA', max_length=2, verbose_name='Tipo de Produto'),
        ),
        migrations.CreateModel(
            name='RequisicaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('tipo_produto', models.CharField(choices=[('MP', 'Matéria-Prima'), ('PI', 'Produto Intermediário'), ('PA', 'Produto Acabado')], default='MP', max_length=2, verbose_name='Tipo de Produto')),
                ('data_requisicao', models.DateField(default=datetime.date.today, verbose_name='Data da Requisição')),
                ('data_necessidade', models.DateField(blank=True, null=True, verbose_name='Data de Necessidade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('atendida', 'Atendida'), ('parcial', 'Parcialmente Atendida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_material_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_material_criadas', to=settings.AUTH_USER_MODEL)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_material', to='core.ordemproducao', verbose_name='Ordem de Produção')),
            ],
            options={
                'verbose_name': 'Requisição de Material',
                'verbose_name_plural': 'Requisições de Material',
                'ordering': ['-data_requisicao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade Solicitada')),
                ('quantidade_atendida', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Quantidade Atendida')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao_material', to='core.produto', verbose_name='Produto')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.requisicaomaterial', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='requisicaomaterial',
            index=models.Index(fields=['numero'], name='core_requis_numero_4dd2be_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaomaterial',
            index=models.Index(fields=['status'], name='core_requis_status_c2db9b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaomaterial',
            index=models.Index(fields=['ordem_producao'], name='core_requis_ordem_p_f297a1_idx'),
        ),
    ]
