# Generated by Django 5.1.7 on 2025-12-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_movimentoentrada_local_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovimentoentrada',
            name='movimenta_terceiros',
            field=models.BooleanField(default=False, help_text='Se marcado, indica entrada/retorno de material de terceiros', verbose_name='Movimenta Terceiros'),
        ),
        migrations.AddField(
            model_name='tipomovimentosaida',
            name='movimenta_terceiros',
            field=models.BooleanField(default=False, help_text='Se marcado, indica saída/remessa de material para terceiros', verbose_name='Movimenta Terceiros'),
        ),
    ]
