# Generated by Django 5.1.7 on 2025-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_tipomovimentoentrada_movimenta_terceiros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovimentoentrada',
            name='tipo_operacao',
            field=models.CharField(choices=[('movto', 'Movimento'), ('op', 'OP/Requisição')], default='movto', help_text='Define se será usado em Movimento ou OP/Requisição', max_length=10, verbose_name='Tipo de Operação'),
        ),
        migrations.AddField(
            model_name='tipomovimentosaida',
            name='tipo_operacao',
            field=models.CharField(choices=[('movto', 'Movimento'), ('op', 'OP/Requisição')], default='movto', help_text='Define se será usado em Movimento ou OP/Requisição', max_length=10, verbose_name='Tipo de Operação'),
        ),
    ]
