# Generated by Django 5.1.7 on 2025-12-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_tipomovimentoentrada_tipo_operacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaomaterial',
            name='tipo_produto',
        ),
        migrations.AddField(
            model_name='requisicaomaterial',
            name='tipo_movimento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='requisicoes_material',
                to='core.tipomovimentosaida',
                verbose_name='Tipo de Movimento'
            ),
        ),
        migrations.AlterField(
            model_name='requisicaomaterial',
            name='ordem_producao',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='requisicoes_material',
                to='core.ordemproducao',
                verbose_name='Ordem de Produção'
            ),
        ),
    ]
