# Generated by Django 5.1.7 on 2025-12-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_requisicaomaterial_tipo_produto_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requisicaomaterial',
            name='core_requis_ordem_p_f297a1_idx',
        ),
        migrations.RemoveField(
            model_name='requisicaomaterial',
            name='ordem_producao',
        ),
        migrations.AddField(
            model_name='requisicaomaterial',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_material', to='core.proposta', verbose_name='Proposta (OP)'),
        ),
        migrations.AddIndex(
            model_name='requisicaomaterial',
            index=models.Index(fields=['proposta'], name='core_requis_propost_890fed_idx'),
        ),
    ]
