# Generated by Django 5.1.7 on 2025-12-31 20:23

from django.db import migrations, models


def migrar_central_para_abertura(apps, schema_editor):
    """
    Migra dados onde folhas='Central' para abertura='central' e limpa folhas.
    """
    Proposta = apps.get_model('core', 'Proposta')
    PortaPavimento = apps.get_model('core', 'PortaPavimento')

    # Migrar propostas com folhas_porta_cabine='Central'
    propostas_cabine = Proposta.objects.filter(folhas_porta_cabine='Central')
    for proposta in propostas_cabine:
        proposta.abertura_cabine = 'central'
        proposta.folhas_porta_cabine = '2'  # valor padrão
        proposta.save(update_fields=['abertura_cabine', 'folhas_porta_cabine'])

    # Migrar propostas com folhas_porta_pavimento='Central'
    propostas_pav = Proposta.objects.filter(folhas_porta_pavimento='Central')
    for proposta in propostas_pav:
        proposta.folhas_porta_pavimento = '2'  # valor padrão
        proposta.save(update_fields=['folhas_porta_pavimento'])

    # Migrar PortaPavimento com folhas='Central'
    portas = PortaPavimento.objects.filter(folhas='Central')
    for porta in portas:
        porta.abertura_porta = 'central'
        porta.folhas = '2'  # valor padrão
        porta.save(update_fields=['abertura_porta', 'folhas'])


def reverter_migracao(apps, schema_editor):
    """
    Reverte a migração (para rollback).
    """
    # Não é possível reverter com precisão, mas isso permite rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_requisicaomaterial_core_requis_ordem_p_f297a1_idx_and_more'),
    ]

    operations = [
        # Primeiro, migrar os dados existentes
        migrations.RunPython(migrar_central_para_abertura, reverter_migracao),

        # Depois, alterar as choices dos campos
        migrations.AlterField(
            model_name='portapavimento',
            name='abertura_porta',
            field=models.CharField(choices=[('direita', 'Direita'), ('esquerda', 'Esquerda'), ('central', 'Central')], default='direita', max_length=10, verbose_name='Abertura da Porta'),
        ),
        migrations.AlterField(
            model_name='portapavimento',
            name='folhas',
            field=models.CharField(blank=True, choices=[('2', '2 Folhas'), ('3', '3 Folhas'), ('4', '4 Folhas')], help_text='Aplicável apenas para portas automáticas', max_length=10, verbose_name='Número de Folhas'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='abertura_cabine',
            field=models.CharField(choices=[('direita', 'Direita'), ('esquerda', 'Esquerda'), ('central', 'Central')], default='direita', max_length=10, verbose_name='Abertura da Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='folhas_porta_cabine',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='Folhas Porta Cabine'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='folhas_porta_pavimento',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='Folhas Porta Pavimento'),
        ),
    ]
