# Generated by Django 5.1.7 on 2025-12-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_abertura_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosgerais',
            name='percentual_indiretos_fabricacao',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Percentual de custos indiretos de fabricação', max_digits=5, verbose_name='Indiretos Fabricação (%)'),
        ),
        migrations.AddField(
            model_name='parametrosgerais',
            name='percentual_instalacao',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Percentual de custo de instalação', max_digits=5, verbose_name='Instalação (%)'),
        ),
        migrations.AddField(
            model_name='parametrosgerais',
            name='percentual_mao_obra',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Percentual de mão de obra sobre o custo de materiais', max_digits=5, verbose_name='Mão de Obra (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='comissao_padrao',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Percentual de comissão sobre o preço', max_digits=5, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='desconto_alcada_1',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Desconto máximo permitido para alçada 1', max_digits=5, verbose_name='Desconto Alçada 1 (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='desconto_alcada_2',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Desconto máximo permitido para alçada 2', max_digits=5, verbose_name='Desconto Alçada 2 (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosgerais',
            name='margem_padrao',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Margem de lucro padrão sobre o custo total', max_digits=5, verbose_name='Margem de Lucro (%)'),
        ),
    ]
