# Generated by Django 5.1.7 on 2025-08-09 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('cabine', 'Cabine'), ('carrinho', 'Carrinho'), ('tracao', 'Tração'), ('sistemas', 'Sistemas')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Regra',
                'verbose_name_plural': 'Categorias de Regras',
                'ordering': ['categoria', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteDerivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('condicoes_inclusao', models.JSONField(default=dict, help_text='Condições para incluir este derivado', verbose_name='Condições de Inclusão')),
                ('codigo_produto_derivado', models.CharField(max_length=50, verbose_name='Código do Produto Derivado')),
                ('tipo_calculo', models.CharField(choices=[('proporcional', 'Proporcional ao Original'), ('fixo', 'Quantidade Fixa'), ('formula', 'Fórmula Customizada')], max_length=20, verbose_name='Tipo de Cálculo')),
                ('multiplicador', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Multiplicador')),
                ('formula_customizada', models.TextField(blank=True, verbose_name='Fórmula Customizada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente Derivado',
                'verbose_name_plural': 'Componentes Derivados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Regra')),
                ('tipo', models.CharField(choices=[('mapeamento', 'Mapeamento Simples'), ('formula', 'Fórmula de Cálculo'), ('condicional', 'Condicional Complexa')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('condicoes', models.JSONField(default=dict, help_text='Condições para aplicar esta regra', verbose_name='Condições')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='Código do Produto')),
                ('formula_quantidade', models.TextField(blank=True, help_text='Ex: pnl.lateral, chp.corpo, largura_cabine + 0.17', verbose_name='Fórmula de Quantidade')),
                ('logica_condicional', models.JSONField(blank=True, default=dict, help_text='JSON com lógica if/else complexa', verbose_name='Lógica Condicional')),
                ('ordem_execucao', models.IntegerField(default=100, verbose_name='Ordem de Execução')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='producao.categoriaregra')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Cálculo',
                'verbose_name_plural': 'Regras de Cálculo',
                'ordering': ['categoria__categoria', 'ordem_execucao', 'nome'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('ativacao', 'Ativação'), ('desativacao', 'Desativação'), ('exclusao', 'Exclusão')], max_length=20)),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='producao.regracalculo')),
            ],
            options={
                'verbose_name': 'Histórico de Regra',
                'verbose_name_plural': 'Históricos de Regras',
                'ordering': ['-data_acao'],
            },
        ),
    ]
