# Generated by Django 5.1.7 on 2025-05-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='custo_instalacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo de Instalação'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='custo_mao_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo de Mão de Obra'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='custo_materiais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo de Materiais'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='custos_detalhados',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custos Detalhados'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ficha_tecnica',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ficha Técnica'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preco_negociado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço Negociado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preco_sem_impostos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço sem Impostos'),
        ),
    ]
