# Generated by Django 5.1.7 on 2025-06-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicopedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='historicopedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='AnexoPedido',
        ),
        migrations.DeleteModel(
            name='HistoricoPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
